### ISSUE TITLE
"url leads to an achive"

### ISSUE THREAD

**Issue by PokeTrainerJoe** [garzj/digi4school#2]
Hi

I tried to download one of the free books which is in a folder (+ Audio and other stuff) and got the message "The provided url leads to an archive."
Is it possible to download books like these, for example "https://digi4school.at/token/5342"

Thanks
Joe

**Comment by garzj** [comment]
Uhh, I didn't think of that case when you need the token url for authentication, but another one to the book itself. I'll have a look today!

**Comment by garzj** [comment]
Should work now!
